### ISSUE TITLE
UI issue for wallet - modal popup

### ISSUE THREAD

**Issue by geopor** [tearust/moderators#45]
Issues with different modal "success" popups:
1. The first letter should be capitalized.
2. There should be no period at the end for a modal pop-up that flashes like this.

<img width="887" alt="Screen Shot 2021-07-21 at 12 56 20 AM" src="https://user-images.githubusercontent.com/86096370/126461844-e7eb73a1-abf6-4e8b-bfff-df4d7ec60409.png">

• Above dialog should read:

Success

<img width="1150" alt="Screen Shot 2021-07-21 at 1 00 40 AM" src="https://user-images.githubusercontent.com/86096370/126461939-e93fcc7c-263d-41da-b56c-850526d22290.png">

• Above dialog should read:

Copied

**Comment by liyangwood** [comment]
fixed.

**Comment by geopor** [comment]
It should be with no period at the end:
Copied

Also please check the faucet page, I still see "success." It should be capital with no period:
Success

**Comment by liyangwood** [comment]
deployed with wallet version 0.0.10

**Comment by geopor** [comment]
<img width="1000" alt="Screen Shot 2021-07-24 at 12 40 38 PM" src="https://user-images.githubusercontent.com/86096370/126879486-0bd3c960-c398-413b-9fb6-4a6f88fbc761.png">

Should read:

Success. Please go back to wallet to check your updated balance.

**Comment by liyangwood** [comment]
fixed with version 0.0.12
